package rules;
dialect  "mvel"

import ftn.sbnz.SbnzProject.model.User
import ftn.sbnz.SbnzProject.model.Gender

rule "BMR Female"
    when
        u: User(gender == Gender.FEMALE)
    then
        u.setBmr(9.247 * u.getWeight() + 3.098 * u.getHeight() - 4.33 * u.getAge() + 447.593);
        update(u)
end

rule "BMR Male"
    when
        u: User(gender == Gender.MALE)
    then
        u.setBmr(13.397 * u.getWeight() + 4.799 * u.getHeight() - 5.677 * u.getAge() + 88.362);
        update(u)
end