package sbnz.integracija;
dialect  "mvel"

import ftn.sbnz.SbnzProject.model.UserDay
import ftn.sbnz.SbnzProject.model.MealRecipe
import ftn.sbnz.SbnzProject.model.Gender
import ftn.sbnz.SbnzProject.model.Notification

rule "Calories deficit"
agenda-group "day-rules"
    when
        $day: UserDay($meals: mealRecipes, $user: user)
        Number (doubleValue < $user.getCalories() - 500) from accumulate(
            MealRecipe(
                $kcal: calories
            ) from $meals,
            sum($kcal)
        )
        $notification: Notification()
    then
        $notification.addToList("You should not eat less than " + ((int) ($user.getCalories() - 500)) + " calories per day");
end

rule "Calories surplus"
agenda-group "day-rules"
    when
        $day: UserDay($meals: mealRecipes, $user: user)
        Number (doubleValue > $user.getCalories() + 500) from accumulate(
            MealRecipe(
                $kcal: calories
            ) from $meals,
            sum($kcal)
        )
        $notification: Notification()
    then
        $notification.addToList("You should not eat more than " + ((int) ($user.getCalories() + 500)) + " calories per day");
end

rule "Amount of sugar Men"
agenda-group "day-rules"
    when
        $day: UserDay($meals: mealRecipes, $user: user, $user.gender == Gender.MALE )
        Number (doubleValue > 37.5) from accumulate(
            MealRecipe(
                $sugar: sugars
            ) from $meals,
            sum($sugar)
        )
        $notification: Notification()
    then
        $notification.addToList("You should not take more than 37.5g of sugar");
end

rule "Amount of sugar Women"
agenda-group "day-rules"
    when
        $day: UserDay($meals: mealRecipes, $user: user, $user.gender == Gender.FEMALE)
        Number (doubleValue > 25) from accumulate(
            MealRecipe(
                $sugar: sugars
            ) from $meals,
            sum($sugar)
        )
        $notification: Notification()
    then
        $notification.addToList("You should not take more than 25g of sugar");
end

rule "Saturated fats"
agenda-group "day-rules"
    when
        $day: UserDay($meals: mealRecipes, $user: user )
        Number (doubleValue > 13) from accumulate(
            MealRecipe(
                $sFat: saturatedFat
            ) from $meals,
            sum($sFat)
        )
        $notification: Notification()
    then
    $notification.addToList("You should not take more than 13g of saturated fats");
end

